name: oct-tutorial
channels:
  - conda-forge
dependencies:
  - ipykernel=6.26.0
  - ipython=8.17.2
  - matplotlib
  - nlopt=2.7
  - pip=24.0
  - python=3.10
  - scipy=1.12.0
  - sympy=1.12.0
  - ipympl=0.9.3
  - ipywidgets=8.1.2
  - qutip=4.7.5
  - pip:
    - krotov==1.2.1
    - weylchamber==0.4.0
